spring.application.name=user-service
# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Artisana_user_service_db
spring.datasource.username=postgres
spring.datasource.password=1994
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration de JPA et Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.cloud.config.enabled=false
# Configuration de la sécurité
spring.security.user.name=admin
spring.security.user.password=password
spring.security.user.roles=ADMIN

# Désactiver la sécurité pour certains endpoints (optionnel)
# Ceci ne remplace pas les antMatchers, mais peut être utile pour des tests
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
